require 'user.settings'
require 'user.keymap'
require 'user.packer'

require 'user.nvim-tree'
require 'user.nvim-lualine'
require 'user.treesitter'
require 'user.telescope'
require 'user.null-ls'
require 'user.gitsigns'
require 'user.lspsaga'
