return {
	{
		"nvim-treesitter/nvim-treesitter",
		version = false,
		build = ":TSUpdate",
		lazy = vim.fn.argc(-1) == 0,
		cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
		opts = {
			ensure_installed = {
				"css",
				"gitcommit",
				"gitignore",
				"go",
				"html",
				"http",
				"javascript",
				"lua",
				"markdown",
				"markdown_inline",
				"nix",
				"rust",
				"scss",
				"sql",
				"typescript",
				"vimdoc",
				"vue",
			},
			highlight = { enable = true },
			indent = { enable = true },
		},
	},
}
